version: '3'
services:
   db:
      image: mariadb:10.4
      container_name: hip_quiz_db
      environment:
        MYSQL_ROOT_PASSWORD: qq0uei
      volumes:
        - "./mount/db:/var/lib/mysql"

   drupal:
      build: drupal_quiz
      container_name: hip_quiz
      ports:
         - "9092:80"
      links:
         - db
